catalystneuro/nwb-conversion-tools

- nwbn_conversion_tools/gui/classes/console_widget.py
- nwbn_conversion_tools/gui/nwbn_conversion_gui.py
extends the explorer tab with an Ipython console on the right side.
It is quite useful to explore the nwbfile in ways that the widgets can't do.
It will automatically load the same file as requested for the NWB-widgets.
> Extend explorer

- nwbn_conversion_tools/gui/command_line.py
- setup.py
creates a console shortcut to open an empty GUI.
```shell
nwbn-gui
```
it might be extended to include optional arguments, such as metadata file path
> console entry point

- nwbn_conversion_tools/converter.py
Changes some NWBConverter methods to make it more generalizable:
1. method create_subject (that can be overridden by child classes)
2. changes in create_nwbfile (particular conversion projects might need to read session_start_time before creating NWBFile)
3. general methods for creating trials tables and adding trials/columns from Pandas dataframes 
4. updated docstrings
> Improve generalization converter

- nwb_conversion_tools/converter.py
- nwb_conversion_tools/gui/nwb_conversion_gui.py
- nwb_conversion_tools/ophys/schnitzerlab/cnmfeconverter.py
- nwb_conversion_tools/ophys/schnitzerlab/extractconverter.py
- nwb_conversion_tools/ophys/sima/simaconverter.py
- nwb_conversion_tools/ophys/suite2p/suite2pconverter.py
use the class to call the run_conversion function within. 
However, i've still kept the older conversion_path, which is redundant, but will only be useful if the user selects another conversion script path from file drop down menu in the gui.
> directly call run_conversion

- nwb_conversion_tools/gui/classes/forms_general.py
metafile.json specifies the experimenter field to be an array, but the forms have a text field only.This change creates a csv string from the list.
> forms_general changes 

- nwb_conversion_tools/__init__.py
@bendichter Not quite as sophisticated as the way SpikeExtractors initializes the extensive list of specialized extractors, but something like this is still necessary for the current file structure.
> quick fix to importing under the new data interface file structure

- nwb_conversion_tools/baserecordingextractorinterface.py
Needed for the tank lab conversion of the SpikeGLX stuff while not population metadata in the main Converter.
> fix requires for passing None metadata into downstream sources

- README.md
https://github.com/NeurodataWithoutBorders/nwb-conversion-tools no longer exists;
https://github.com/catalystneuro/nwb-conversion-tools will work
> Fixed dead link in README

- nwb_conversion_tools/basedatainterface.py
- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
- nwb_conversion_tools/nwbconverter.py
- nwb_conversion_tools/utils.py
- setup.py
@bendichter The first of the major metadata handling changes is included in this PR. Subsequent ones will include the `NeuroscopeSorting` and `SpikeGLXRecording`.
Overall changes are built to reflect the structural shift of metadata auto-population away from specific `NWBConverter`s into the individual `DataInterfaces`.
This will render several past conversion scripts in other repositories incompatible with the current design; I have locally saved a branch of the current pre-metadata patch on my end for quick side-reversion, if that is ever needed for those conversions.
@luiztauffer I will also be uploading an example `RecordingExtractor` template tomorrow that uses this structure and showcases how, per our discussion, it ought to flow to keep an eye out for that. Also let me know if this …
> Refactor interface metadata

- nwb_conversion_tools/basesortingextractorinterface.py
This fix resolves some very odd issues caused by any sorting extractor that doesn't contain spikes in what was previously the first 100 seconds of the experiment; also more holistically generalized the `end_frame` for stubbing that will now include at least one spike (and very slightly more) for every unit.
Also adjusted indenting style.
> improved the stubbing of the BaseSortingExtractor

- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
Though in principle, it appears as if the [SpikeGLX can have multiple shanks](https://github.com/billkarsh/SpikeGLX/blob/master/Markdown/UserManual.md#shank-map), the exact formatting of the channel mapping and extraction thereof would be unreliable without a good prototype file to test on.
The current implementation uses the default maps of single shanks.
> get_metadata() for SpikeGLX

- nwb_conversion_tools/basesortingextractorinterface.py
@bendichter Extended sorting interface to include capability of writing electrode metadata in the absence of a true recording extractor. This removes the need for a NoRecording interface on the conversions that currently make use of it.
I did begin this approach by attempting to refactor the NwbRecordingExtractor.add_* methods into a general, non-class specific form so that they could be used in both that and the NwbSortingExtractor, and it worked well up until add_electrodes, which is intertwined with its recording extractor object at nearly every update to the keyword arguments for nwbfile.add_electrode, so was unable to generalize it on that repo.
I believe this current interface specific approach is far simpler, however, and even has the same capabilities for filling missing data as …
> Sorting interface to write electrode metadata without recording

- nwb_conversion_tools/basedatainterface.py
- nwb_conversion_tools/baserecordingextractorinterface.py
- nwb_conversion_tools/datainterfaces/intandatainterface.py
- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
- nwb_conversion_tools/json_schema_utils.py
- nwb_conversion_tools/nwbconverter.py
- setup.py
@bendichter @luiztauffer The new json schema validation, while very nice and general, produced a number of errors that I've begun to correct here and in the Tank repo first.
The biggest changes are related to the now very heavy usage of `get_schema_from_method_signature` coupled  with the fact that not all downstream `properties` are of type `string`, as was previously hard-coded. Extended this to at least include type `bool` and throw an error if not either of those types to let us know to implement it.
While the actual `param_type` checking is the biggest direct change, there are a number of indirect changes required across the repo as well as coding practices for downstream inheritances. This is due to the usage derived from `param.annotation` which requires much better specification …
> debugging for nwb-conversion-tools v0.6.0

- nwb_conversion_tools/json_schema_utils.py
- nwb_conversion_tools/nwbconverter.py
@luiztauffer when a `DataInterface.get_metadata_schema` returns values like `$shema` and `id_`, these values should only be on the root level of a json-schema object. When it gets merged with other schemas, it should lose these identifiers. Would this PR work for you?
> unroot schema

- nwb_conversion_tools/utils.py
Changes on `get_schema_from_hdmf_class()`:
> get_float_type_in_docval

- nwb_conversion_tools/json_schema_utils.py
@bendichter Some of the annotation types in `spikeextractors` are fancier in their extensions using `typing.Union` to include things like `Path`, `None`, etc., in addition to something obvious like a `str`. This threw off the original annotation type checking, of course, so this fixes it in a _fairly_ general manner by finding the common base data type and validating against that (assuming there is one and only one match with the base data type).
One interesting case that would break this, which we _may_ run into in the future with the method attached here is an `ArrayLike` annotation, which can include more than one of the allowable json types (`int`, `float`, `list`) but could still be valid in that mapping as a json `array`. Depends on how the A`rrayLike` call is implemented as well, …
> Extend annotation checking to union

- nwb_conversion_tools/json_schema_utils.py
- tests/test_json_schema_utils.py
@bendichter @weiglszonja Quick hotfix needed for running nwb-conversion-tools when the annotation types don't have internal __args__ attribute.
> fixed issue with reading annotations without __args__ attr

- nwb_conversion_tools/datainterfaces/intandatainterface.py
- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
@bendichter Using a similar strategy to spikeextractors, this allows the format specific interfaces that use specific outside packages to import them without having to add the packages to the main requirements.
Currently the only two interfaces that do this are intan and neuroscope, but it sets the precedent early on do always use this strategy to avoid bloating the nwb-conversion-tools `setup`.
> Using lazy imports to avoid having to append strict requirements

- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
@bendichter Simple wrapper for the [NeuroscopeMultiRecording extractor](https://github.com/SpikeInterface/spikeextractors/pull/512); inherits all relevant methods from its related single recording extractor, with the only conflict requiring generalization being the determination of the `session_path` from either the `file_path` or the `folder_path` argument.
> added and debugged neuroscope multi recording interface

- nwb_conversion_tools/baserecordingextractorinterface.py
- nwb_conversion_tools/json_schema_utils.py
- nwb_conversion_tools/nwbconverter.py
@bendichter This PR adds some stuff relevant to Syntalos
1. Allow timestamps arguments to be passed to recording extractor
2. Refactored that part of the new annotations fix you didn't like
3. Small bug fix to the default `session_start_time`; apparently if it's `datetime(1900,1,1)` you get really weird, hard to debug errors during the final `io.write` because the associated timestamp becomes negative. Updating this to `datetime(2000,1,1)` fixes that bug.
> Annotation refactor; remove intan naming; fix default session start time

- nwb_conversion_tools/json_schema_utils.py
@bendichter Very minor correction; technically, if you enter this assertion, the field `.__args__` may not exist, and if so that is the error that is returned instead of the more informative one.
> fixed incorrect error message display

- nwb_conversion_tools/datainterfaces/__init__.py
@bendichter For the spikeextractor data interfaces with more than one class within them, changing the `__init__` imports to `*` to reduce code and mimic roiextractors
> updated data interface import structure to be similar to roi

- nwb_conversion_tools/conversion_tools.py
- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
- tests/test_tools.py
@bendichter Small debugs for Petersen
1) For those sessions of Petersen that did not have spike sorted data, there apparently is no `.xml` field for isolating the channel groups used for `spikeDetection`, which is necessary for LFP/DAT extraction due to the channel subsetting. This adjusts the subsetting in this case to occur at the anatomical level.
2) Added that timestamp regularity check we talked about [here](https://github.com/catalystneuro/buzsaki-lab-to-nwb/pull/25).
> Debugging for petersen; add timestamp regularity check

- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
@bendichter Small fix required for Manuel's use of the pipeline.
It appears as if, when the fileCreateTime field was added for the session_start_time extraction, it was not checked against the possibility of a SubRecording being the extractor type.
> Spikeglx metadata fix

- nwb_conversion_tools/baserecordingextractorinterface.py
- requirements.txt
@alejoe91 @luiztauffer Depends on https://github.com/SpikeInterface/spikeextractors/pull/578
The `buffer_mb` argument has been available at the `add_electrical_series` level for quite a while, but was never able to be specified at the highest level of `write_recording`.
Now that we are running multiple large-scale raw data conversions in parallel, a facet unlikely to soon change, this argument will give us a much greater degree of control over the processing resource specification.
> propagate buffer_mb argument from spikeextractors

- nwb_conversion_tools/conversion_tools.py
- nwb_conversion_tools/nwbconverter.py
- setup.py
fix #147 
@luiztauffer Please check if this fixes your issues with Movshon separately from the appropriate intended use of retrieving `metadata` from `get_metadata()`
These `conversion_tool` functions will also be useful reference functions for the NwbExtractors on SpikeInterface (and possibly ROIExtractors, I'd assume), reducing that code usage across the ecosystem and centralizing the standardization for the default values.
> Fix default nwbfile

- nwb_conversion_tools/baselfpextractorinterface.py
- nwb_conversion_tools/baserecordingextractorinterface.py
- setup.py
@luiztauffer [When I propagated the `buffer_mb` option](https://github.com/catalystneuro/nwb-conversion-tools/pull/137) from spikeextractors to the recording class, I forgot to also propagate it to the LFP interfaces that inherit from it, but override that function in order to specify the lfp specific option.
> small fix to arguments for recording and lfp interfaces

- nwb_conversion_tools/baserecordingextractorinterface.py
- nwb_conversion_tools/basesortingextractorinterface.py
- nwb_conversion_tools/conversion_tools.py
- nwb_conversion_tools/datainterfaces/blackrockdatainterface.py
- nwb_conversion_tools/json_schema_utils.py
- nwb_conversion_tools/nwbconverter.py
- setup.py
@sbuergers [found out](https://github.com/catalystneuro/nwb-conversion-tools/pull/166#discussion_r610653741) we were not defining `Device` and `ElectrodeGorup` as arrays on the base schema.
```python
from jsonschema import validate
#import any Converter using BaseRecordingExtractorInterfaces
converter = MyNWBConverter()
validate(instance=converter.get_metadata(), schema=converter.get_metadata_schema())
```
> define type of arrays for ecephys schema

- nwb_conversion_tools/utils/spike_interface.py
- tests/test_si.py
We recently moved the write_recording method from spikeextractors to nwb-conversion-tools, but lost that rich testing infrastructure that spikeinterface uses. This is the start of restoring that on our end.
```
!pytest  # from the working directory of the repository
```
> adding spikeextractors tests for nwb, including new metadata

- nwb_conversion_tools/basedatainterface.py
- nwb_conversion_tools/datainterfaces/blackrockdatainterface.py
- nwb_conversion_tools/nwbconverter.py
> get_conversion_options() method and some datainterface updates

- nwb_conversion_tools/nwbconverter.py
fix [#190](https://github.com/catalystneuro/nwb-conversion-tools/issues/190)
1. allow metadata to be optional for `Converter.run_conversion()`. If not passed by the user, Converter will use the basic metadata formed with `Converter.get_metadata()`
2. validate metadata before running conversion. This will help us catch metadata-related errors before conversion starts
All conversion tests will necessarily go through this
> metadata as optional and validated

- nwb_conversion_tools/baselfpextractorinterface.py
- nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
Accommodate the possibility of writing spikeglx traces as raw (`ap` extension) or lfp (`lf` extension). 
@CodyCBakerPhD I think this will be important for Brody lab [here](https://github.com/catalystneuro/brody-lab-to-nwb/pull/5).
I tested on MovshonSpikeGLXConverter and it is working over [there](https://github.com/catalystneuro/movshon-lab-to-nwb/blob/main/tutorials/spikeglx_nwb_conversion_simple.ipynb).
> Fixes for SpikeGLX

- nwb_conversion_tools/datainterfaces/blackrockdatainterface.py
- nwb_conversion_tools/datainterfaces/openephysdatainterface.py
- nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
fix names of dictionaries and remove additionalProperties in `Converter.get_source_schema()` for Blackrock, Openephys and SpikeGLX
> No additonal properties

- nwb_conversion_tools/utils/spike_interface.py
- requirements-dev.txt
- tests/test_si.py
This is a PR for some minor fixes over the #181 which were overlooked.
Setting property  'brain_area'  for `recordingextractor `was not being correctly written as a location property for the nwb file electrodes table. 
'group_name' property was not correctly overriding the `recordingextractor's `'group' property while writing the group/group_name for the nwbfile electrodes table.  
Have updated the test files.
> fixes for write_electrodes for properties: group_name and location

- setup.py
`psutil` is a requirement but not listed in the setup.py dependencies (https://github.com/catalystneuro/nwb-conversion-tools/issues/203).
After pip installing the package on a new env:
```
import nwb_conversion_tools 
```
throws an error (https://github.com/catalystneuro/nwb-conversion-tools/blob/master/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py#L4)
> Add psutil in setup.py dependencies

- nwb_conversion_tools/utils/metadata.py
- setup.py
- tests/metadata_tests.json
- tests/metadata_tests.yml
- tests/test_json_schema_utils.py
Convenient util function to load metadata from yaml and json files
The `load_metadata_from_file()` function will be helpful any time a script might load the user-customized metadata from files (which can cbe yaml or json). 
For example, when running the conversion scripts [from command line](https://github.com/catalystneuro/movshon-lab-to-nwb/blob/6b705c24615c098399ca0c48c0535f6564d67f1d/scripts/convert_blackrock.py#L23) that is the only feasible way of passing user metadata. Of course this can be used in any notebook or other script as well.
> load metadata from file

- nwb_conversion_tools/utils/spike_interface.py
fix #207 
In v0.8.5 of nwb-conversion-tools, it is possible for a RecordingExtractor object to have a `starting_time` value that is not a `float` as expected of `pynwb.ecephys.ElectricalSeries` part of the `utils.spike_interface.write_recording(...)`.
This fixes it by hard casting the value at time of write within `utils.spike_interface.write_recording(...)`.
```
import spikeextractors as se
from nwb_conversion_tools.utils.spike_interface import write_recording
from pynwb import NWBHDF5IO
nwbfile_path = ".../test.nwb"
recording_extractor = se.example_datasets.toy_example()[0]
recording_extractor._times = [int(1)]
write_recording(recording=recording_extractor, save_path=nwbfile_path, overwrite=True)
with NWBHDF5IO(path=nwbfile_path, mode="r") as io:
out_nwbfile = io.read() …
```
> fixing issue 207

- nwb_conversion_tools/utils/json_schema.py
- tests/test_interfaces.py
- tests/test_si.py
* offer more explicit error when type mapping cannot be found
* use parameterize to separate out tests for different interfaces
> minor testing improvements

- nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
- nwb_conversion_tools/utils/conversion_tools.py
in axondadatainterface.py:
* run BLACK
* change name of "generate_position_data" to "get_position_object"
* explicitly define __init__ for AxonaRecordingExtarctor
* generate source schema from explicit AxonaRecordingExtarctor.__init__
in conversion_tools.py, use nwb.processing instead of deprecated nwb.modules
What was the reasoning behind this change? Please explain the changes briefly.
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```
> axona style suggestions

- nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
This is related to PR https://github.com/SpikeInterface/spikeextractors/pull/659
To handle the above problem, the same arguments (nsx_override/nev_override) provided by `neo.BlackrockIO` should also be exposed at the blackrockdatainterface arguments.
> Blackrock interface updated kwargs

- nwb_conversion_tools/utils/spike_interface.py
- tests/test_si.py
[fix #196](https://github.com/catalystneuro/nwb-conversion-tools/issues/196) 
Allowing user control over write options for `ecephys` electrical series in order to speed the process in certain cases.
New tests have been added for each option, as well as time reporting for write speed comparison.
```
!pytest
```
> enhanced add_electrical_series

- nwb_conversion_tools/utils/specdatachunkiterator.py
I was thinking of some structural changes to the class `SpecDataChunkIterator`:
- making `SpecDataChunkIterator` as an abstract class
- the child classes would be specific for the underlying object containing the data (could be a Iterable/extractor object etc)
- keeping all the other logic that @CodyCBakerPhD has implemented
> create abstract data chunk iterator for various downstream data types

- nwb_conversion_tools/utils/spike_interface.py
There are two small fixes that I'm proposing in this PR for the `add_electrodes()` method of spike_interface:
-  Bug fix: to find the dtype of the electrical series the channel_ids should be one from the list of `extractor.get_channel_ids()` and not default to 0. [Here ](https://github.com/catalystneuro/nwb-conversion-tools/pull/222/commits/93b8a23cc39215898c26e192f58fc0a84874dc1b)
- Enhancement: having the functionality to enter a custom `starting_time` for the `ElectricalSeries`. [Here](https://github.com/catalystneuro/nwb-conversion-tools/pull/222/commits/5d4391c7328a8d32bf31d553410c2ec226f99ac5)
> channel ids for dtype bug fix

- nwb_conversion_tools/utils/conversion_tools.py
- tests/test_tools.py
Hidden behind some recent changes to control over electrical series writing of RecordingExtractor objects (and some future DataChunking changes as well) was an assumed speed increase. This adds a conversion tool that anyone can use to confirm it, but more usefully returns the estimated amount of time the entire conversion will take - which is nice to have for hefty conversions that can take on the order of hours.
Basic tests for the function have been added to ensure it runs without error, but truly useful information would come from more extensive local testing that I don't want to force the CI to do every single push.
Here's an all-encompassing code block that tests the speed differences of some of the recent changes.
```
import numpy as np
from spikeextractors import …
```
> Add speed testing for writing recordings

- nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
BaseLFPExtractorInterface makes minor modifications to BaseRecordingExtractorInterface, i.e. adding `ElectricalSeries_lfp` to the metadata and converting as `lfp` data. However, it does not change the metadata schema appropriately (i.e. including `ElectricalSeries_lfp`), thus failing the metadata schema validation. Here we include `ElectricalSeries_lfp` in the metadata schema.
> add ElectricalSeries_lfp to get_metadata_schema in BaseLFPExtractorInterface

- tests/test_gin.py
GIN data has been available for SpikeGLX for some time; finally getting around to adding it here to verify the metadata is being handled correctly and roundtrip works without error.
GIN tests added, interface debugged.
```
!pytest
```
> Add SpikeGLX GIN

- .github/workflows/ci-development.yml
- .github/workflows/ci-full.yml
- .github/workflows/ci-production.yml
The codecov runs and uploads from the lazy test pipeline do not count the results of GIN tests and so falsely report massive decreases to coverage. Also, in general, unnecessarily duplicates the number of codecov uploads. This PR removes them.
The PR also adds coverage for the other operating systems; however, reading on [pricing for GitHub actions](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions), at least for private repo's, the mac system in particular is billed 10x as much as the linux, and with our current test run speeds we could eat that up very quickly. Since we're a public repo I think we still get as much as we want for free, but if @bendichter could triple check under `settings -> billing` to make sure that is the case
No …
> removing spurious codecov runs; expanding OS coverage

- requirements-dev.txt
- tests/test_gin.py
Adding OpenEphysRecording tests. Having trouble getting second ('binary') tests to pass on local versions of the GIN files (unbound file error somewhere in the messages of pyopenephys). Seeing if this occurs with datalad.
```
pytest
```
> Adding OpenEphys tests

- nwb_conversion_tools/datainterfaces/__init__.py
- nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- tests/test_gin.py
Adding SortingInterface GIN test framework, starting with the PhySortingInterface tests. There is some pickling error occurring from spikeextractors occurring during the equality check when I run locally, seeing if it occurs on Linux as well.
```
pytest
```
> Add phy gin

- nwb_conversion_tools/utils/json_schema.py
Minor PEP8 warnings from `json_schema` in our `utils`.
1. `l` is ambiguous as a keyword [E741](https://www.flake8rules.com/rules/E741.html). Changing to `ls` instead.
2. Our `numpy` docstrings should always be in the imperative mood and should not start with 'Return'. Easy way to think of this is the docstring tells the user what the function _does_, not _how_ it works.
No changes to behavior.
> fixing pep8 violations in json_schema

- nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- tests/test_gin.py
Latest changes broke BlackrockRecordingExtractorInterface.
@Saksham20 I reverted back your changes, because locally for me they broke the conversion, due to older spikeextractor not being able to deal with multiple streams. I believe your changes had the newer SI/NEO in mind?
I left them commented out for easy reference, cloud you please check them out?
```
from movshon_lab_to_nwb import MovshonBlackrockNWBConverter
from pathlib import Path
base_path = Path('/home/luiz/storage/taufferconsulting/client_ben/project_movshon/data_blackrock_0/')
file_recording_raw = str(base_path / 'XX_LE_textures_20191128_002.ns6')
file_recording_processed = str(base_path / 'XX_LE_textures_20191128_002.ns3')
file_sorting = str(base_path / 'XX_LE_textures_20191128_002.nev')
source_data = dict( …
```
> adding nsx_to_load as arg for Blackrock files. Fixing tests

- nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
- nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
- nwb_conversion_tools/datainterfaces/ophys/caiman/caimandatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/cnmfe/cnmfedatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/extract/extractdatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/hdf5/hdf5datainterface.py
- nwb_conversion_tools/datainterfaces/ophys/sbx/sbxdatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/sima/simadatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/suite2p/suite2pdatainterface.py
- nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py
- nwb_conversion_tools/utils/json_schema.py
- nwb_conversion_tools/utils/spike_interface.py
- tests/test_si.py
We have recently enforced local control of method signature for the automated setting of source schemas for `ecephys` interfaces - this primarily extends it to the `ophys` interfaces as well removes a few random references to unspecified PathTypes that were previously missed.
All references to PathType across the repo should now be properly specified as `FilePathType`, `OptionalFilePathType`, or `FolderPathType` and import these directly from the utils rather than redefining them every time.
No changes to actual tests, but they are quite useful in checking that nothing gets broken with the update.
```
pytest
```
> Fix remaining annotations

- nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
- tests/test_interfaces.py
Adding tests for one of our remaining untested interfaces; the SpikeInterface `.pkl` file interface.
There's no GIN data for it, not that we would need it since we can just generate synthetic data similar to the tutorial interfaces.
```
pytest
```
> Add SpikeInterface .pkl tests

- nwb_conversion_tools/basedatainterface.py
- nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
- tests/test_converter.py
I noticed that, as of PR #257, all of our BaseDataInterfaces use direct schema generation from class initialization arguments. This, therefore, generalizes it to always apply in place of a base_schema for the abstract DataInterface.
No behavior change
> generalized get_source_schema() across all interfaces

- nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
Noticed in the most recent Buzsaki conversion that the group number increment is shifted twice on accident. This is most noticeable on a linear probe, where we know we only have one group but it shows up listed as `Group2`. Less noticeable for multi-shank experiments, which is why we didn't see this before.
It's on the to-do list to standardize all metadata appearance across interfaces and to automatically check that default structure as well as manually overridden items. Either way, it would catch this kind of thing across the repo.
> Fix Neuroscope group increments

- nwb_conversion_tools/utils/genericdatachunkiterator.py
- tests/test_gin.py
Moderate performance increase and massive code simplification based on suggestions by @bendichter. Pending other suggestions, this will also be the form of the class I'll submit upstream to `hdmf`. It's come a long way from the first versions and now that it's pared down to basics, I can't think of anything left that would increase performance from this side of things.
Performance test on a 957.5s SpikeGLX example file (384 channels) using default chunk/buffer sizes (1MB/1GB, respectively)...
- New method: ~592s
- Previous method (master branch):  ~624s
This raises the speed efficiency to ~161% of relative recording length for Neuropixels, meaning we can write a minute of such data in around ~37s.
Details from top to bottom;
1. Updated default shape setters to return their values rather …
> GenericDataChunkIterator improvements

- nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
- nwb_conversion_tools/utils/basenwbephyswriter.py
- tests/test_interfaces.py
The PR merge #230 did not take care of the ability to pass 'UnitProperty' metadata to any `sortingextractorinterface`. It was expecting any custom properties to exist in `self.metadata["units"]=dict(prop1='desc', prop2='desc2')`. The old way of doing this was `self.metadata["Ecephys"]["UnitProperties"]= dict(prop1='desc', prop2='desc2')`.
This PR adds this back. 
The below, should run with a specific `sortingextractorinterface`
```python
from jsonschema import validate
metadata = sortingextractorinterface.get_metadata()
metadata["Ecephys"] = dict(UnitProperties=[dict(name='prop_name1', description='description1'), 
dict(name='prop_name1', description='description1')])
validate(instance= metadata, schema=sortingextractorinterface.get_metadata_schema()) # this should run fine …
```
> re-adding UnitProperties to metadata schema in SortingExtractorInterface

- nwb_conversion_tools/utils/json_schema.py
- tests/test_json_schema_utils.py
Fix #314 
This PR fixes the bug found in updating two dicts (dict a, b) when there is a non existing key in dict a but dict b has the value of the key as a list.
> deep_dict_update list appending bug fix in default converter

- nwb_conversion_tools/basedatainterface.py
A long time ago, we renamed `convert_data` to `run_conversion` to match the syntax between `DataInterfaces` and the `NWBConverter`. We provided a deprecation warning for this change for at least six months, and with the new major version so much else is changing we might as well get around to actually removing this.
Also added some missing docstrings while I was working in that class.
> Remove convert_data() deprecation warning

- requirements-full.txt
- requirements-minimal.txt
- requirements-rtd.txt
GitHub alerted a security issue within `lxml`, which we use for the Neuroscope interfaces. Simple fix is to bump version on `lxml`.
> Update lxml version

- nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
- nwb_conversion_tools/utils/basenwbephyswriter.py
- nwb_conversion_tools/utils/basesinwbephyswriter.py
- nwb_conversion_tools/utils/ephys_writer.py
- nwb_conversion_tools/utils/neonwbephyswriter.py
- nwb_conversion_tools/utils/si013nwbephyswriter.py
- nwb_conversion_tools/utils/si090nwbephyswriter.py
- tests/test_internals/test_si013.py
- tests/test_internals/test_si090.py
fix #320
Change the behavior of `stub=True` slicing in channels dimension. Now it only slices in the time dimension.
> remove channels' slicing in stub

- tests/test_on_data/GIN_converter_specification.yml
- tests/test_on_data/test_yaml_conversion_specification.py
Another simple pre-PR for the YAML conversion specification. In particular, this includes the actual example YAML file we use in the main PR for running a full conversion
The primary test here is if the defined YAML specification schema is valid and compatible with our example file, or vice versa.
> Add example YAML conversion specification instance

- nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
- nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
- requirements-full.txt
- tests/test_internals/test_interfaces.py
- tests/test_on_data/test_gin.py
Restores input mapping of `file_path` type arguments to the single standard.
Tests are properly adjusted to refer to new `file_path` convention, but follow up PR still needs to restore certain interface tests.
> Restoring remapping of input keys

- nwb_conversion_tools/utils/json_schema.py
- tests/test_internals/test_json_schema_utils.py
Restoring `deep_dict_update` changes for handling list appending, and accompanying tests.
> Restore deep dictionary changes and tests

- nwb_conversion_tools/utils/recordingextractordatachunkiterator.py
Enhancing docstrings for the `RecordingExtractorDataChunkIterator` class.
No change to behavior.
> Docstrings for RecordingExtractorDataChunkIterator

- nwb_conversion_tools/utils/spike_interface.py
from warning:
>  /home/runner/work/nwb-conversion-tools/nwb-conversion-tools/nwb_conversion_tools/utils/spike_interface.py:368: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
chan_data = np.float(chan_data)
> change from np.float to float

- nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
- nwb_conversion_tools/utils/spike_interface.py
- tests/test_internals/test_si.py
Fix https://github.com/catalystneuro/nwb-conversion-tools/pull/368
Add `write_electrical_series` option to `write_recording` to optionally avoid writing time series .
```
write_recording(..., write_electrical_series=False)
```
> Add write_electrical_series option to write_recording

- requirements-full.txt
- requirements-minimal.txt
Some recent changes to the master branch of `spikeinterface/spikeextractors` broke the Intan interfaces; not only for PR #370 , but also on `nwb-conversion-tools/main`. Instead of listing unreleased requirements as pointing to branches (which can change), updating them to point to specific hashes; specifically, those before the offending changes were merged.
Attn: @alejoe91 - If you could look into fixing this ASAP so not only #370 works, but so that this bug doesn't continue further into future hash updates and even releases. See https://github.com/catalystneuro/nwb-conversion-tools/runs/4844537233?check_suite_focus=true for traceback reference. I also reproduced in a fresh environment with current `spikeextractors` master.
> Version pin dev versions of spikeextractors and spikeinterface

- nwb_conversion_tools/utils/spike_interface.py
- requirements-full.txt
- requirements-minimal.txt
Fix https://github.com/catalystneuro/nwb-conversion-tools/issues/369
Remove unused code and code to retrieve correct gains and offsets for old extractors as now it's done in the `OldToNewRecording` (https://github.com/SpikeInterface/spikeinterface/pull/462)
```
import spikeextractors as se
from nwb_conversion_tools import write_recording
rec, sort = se.example_datasets.toy_example()
rec.set_channel_gains(0.1)
rec_sub = se.SubRecordingExtractor(end_frame=100)
write_recording(rec_sub, save_path="test_gains.nwb")
```
> Remove gain correction for old SI

- nwb_conversion_tools/utils/spike_interface.py
returning the nwbfile object in write_recording and write_sorting allows us to build the nwbfile in memory
> return nwbfile

- README.md
- tests/test_on_data/test_gin.py
- tests/test_on_data/test_gin_ophys.py
Allows the output of GIN tests to be saved to a non-temporary folder (should be disabled by default on `main`, and only recommended for these kinds of review purposes).
I've uploaded the output from the most up-to-date version to slack (GitHub won't let me do it here).
In `test_gin.py`, simply flip the flag `SAVE_OUTPUTS` and adjust the `OUTPUT_PATH` as desired.
> Save output from GIN tests

- requirements-full.txt
- requirements-minimal.txt
- tests/test_on_data/test_gin_ecephys.py
Recently discovered that when gains are set to an old RecordingExtractor, the newly refactored code for writing ElectricalSeries sometimes upcasts the data type to `float` due to a bug in the `OldToNewRecording` functions on spikeinterface. This PR adds explicit tests for this behavior and will point to a fix on SI to ensure it works.
Also attached some style suggestions for previous test written by @h-mayorquin
> Add tests for Neuroscope dtype

- nwb_conversion_tools/utils/spike_interface.py
Quick bug?
Some of the `add_device` functions in the utils for `spikeinterface` contain the recording argument that was removed before (discussed in the closed pull request #377). It seems that some of those were still there.
> removed unnecessary argument in add_device

- .github/workflows/testing-linux.yml
- requirements-full.txt
- requirements-minimal.txt
- requirements-rtd.txt
Only two things we need to iron out before doing a new release of `nwb-conversion-tools` is (a) pin to newest release of SE and make sure everything works (lots of various bug fixes there for certain extractors), and (b) get a new release of SpikeInterface and pin to that (lots of bug fixes for new API usage and `old_to_new` API utils).
> Testing SpikeExtractors latest version pin

- nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
- nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
- tests/test_on_data/test_gin_ecephys.py
This should fix #382
As discussed in the issue there is a shape mismatch between gains when the spikeinterface transforms a spikeextractor object to a spikeinterface one. The mismatch occurs when some of the channels are subset and the example in the issue was for neuroscope.
I was discussed with @bendichter yesterday and he mentioned that it would be a good idea to just change fully to `spikeinterface` for neuroscope as we intend to do it anyway at some point. This pull request is the first attempt in this direction and I start by implementing @alejoe91 suggestion in the issue to showcase some problems, discuss and get your feedback.
There are three modifications in the diff:
1) As per @alejoe91  suggestion the `subset_shank_channels` method in the neuroscope interface has been modified …
> Modify neuroscope to use spike interface

- make_env.yml
Small changes to make the conda environment file `make_env.yml` track the setup file and therefore minimal-requirements.txt.
Follow the installation instructions for conda in the readme and that should provide an environment with the minimal installation.
> modify conda_env_to_track the setup file

- nwb_conversion_tools/datainterfaces/behavior/movie/movie_utils.py
- nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
- tests/test_internals/test_movie_utils.py
Pointed out by @CodyCBakerPhD [here](https://github.com/catalystneuro/nwb-conversion-tools/pull/414#issuecomment-1059996959), opencv returns frame in BGR instead of RGB. This PR is a quick fix for this.
```python
import skvideo.io
from nwb_conversion_tools.datainterfaces.behavior.movie.movie_utils import VideoCaptureContext
import numpy.testing as npt
video_path = "path/video.mp4"
with VideoCaptureContext(file_path=video_path) as vw:
frame0_bgr = vw.get_movie_frame(0)
reader = skvideo.io.FFmpegReader(video_path, inputdict=dict(), outputdict=dict())
for frame in reader.nextFrame():
frame0_rgb = frame
break
print(npt.assert_array_equal(frame0_rgb[:,:,0], frame0_bgr[:,:,0]))
print(npt.assert_array_equal(frame0_rgb[:,:,-1], frame0_bgr[:,:,0])) # without this fix
```
ground truth : …
> bgr to rgb

- .github/workflows/testing-linux.yml
- .github/workflows/update-testing-data.yml
- tests/test_internals/test_movie_interface.py
- tests/test_on_data/test_gin_behavior.py
Now that behavior datasets are up on GIN (done correctly with annexed datasets) [here](https://gin.g-node.org/CatalystNeuro/behavior_testing_data), its better that tests for `MovieDataInterface` rely on those video files rather than creating on the fly with OpenCV. 
Have moved the old `tests/test_internals/test_movie_interface.py` to `tests/tests_on_data/test_gin_behavior.py`.
> create moviedatainterface tests with GIN data

- nwb_conversion_tools/tools/spikeinterface/spikeinterfacerecordingdatachunkiterator.py
Somehow this got missed when we altered the import to the `hdmf.data_utils.GenericDataChunkIterator`.
This adds it back in.
Option is usable without any further changes via
```python
conversion_options=dict(name_of_data_class_alias=dict(iterator_opts=dict(display_progress=True)))
```
> Enabled progress bar option for SIRecordingIterator

- src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
- tests/test_internals/test_si.py
- tests/test_on_data/test_gin_ecephys.py
While I was working with a `spikelgx` conversion I realize that our current implementation of `add_electrodes` overwrites the property of channel name if this is available in the recording object (it always assign it to `channel_ids.astype("str")`). 
I modified the logic so this does not happen and added a new test.
I also did other two things in this PR:
* corrected a small bug that was showing up in warnings.
* Split one of the unit tests in two as it was testing two different things in one function.
* Added more descriptive names to the unittests.
> Not overwriting channel name if recording object has the property

- setup.py
Simple PR for not overwriting the `gin_test_config.json`  file if it already exists. 
Also, the option `package_data={"": ["template_metafile.yml"]}` seems to not be used in the setup. The argument `include_package_data` seems to be doing the job already, see the [documentation](https://setuptools.pypa.io/en/latest/userguide/datafiles.html). Moreover, I looked through the repo history with git blame and could not find the `template_metafile.yml`. Also, see this strong accusation:
http://blog.codekills.net/2011/07/15/lies,-more-lies-and-python-packaging-documentation-on--package_data-/
Maybe I am missing something though. Let's see what the CI says.
> Update setup to avoid overwriting existing gin_test_config

- src/nwb_conversion_tools/utils/json_schema.py
Small fix I ran across when finalizing my Tingley conversion prototypes
> [Bug]: add keywords to base NWB metadata schema

- .github/workflows/add-to-dashboard.yml
With the new org-wide To-Do list, it would be nice to have an automatic setting feature for new Issues/PRs.
Unfortunately this isn't the kind of thing that can be set at the `ISSUE_TEMPLATE` level but instead has this lovely workflow. GitHub may eventually had implicit project-side workflows for doing this, but hey that's why it's still in Beta.
> [Workflow]: Automatic adding of Issues/PRs to Dashboard

- .github/workflows/testing.yml
- .github/workflows/update-caches.yml
- setup.py
- src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
- src/nwb_conversion_tools/nwbconverter.py
- tests/test_on_data/test_gin_behavior.py
Right now, when we run a conversion (with `NwbConverter` class) and we pass some `conversion_options` this overrides all of them:
https://github.com/catalystneuro/nwb-conversion-tools/blob/673410a79402b31a919e0e13e2bf7ed84732d15c/src/nwb_conversion_tools/nwbconverter.py#L149-L150
The current PR solves this by using `dict_deep_update` so the defaults conversion options defined at the interface level are respected at run time.
This PR is a follow up of #465 where we are using the `get_conversion_options` to hard code how and where the recording extractor data should be written. 
Currently, we only define `get_conversion_options` for spikeglx and in our `TutorialRecordingExtractor` but if we want to use this option further we will need something like this.
> Update default conversion options instead of overwriting for run conversion

- nwb_conversion_tools/datainterfaces/icephys/baseicephysinterface.py
- nwb_conversion_tools/tools/neo/neo.py
- nwb_conversion_tools/utils/json_schema.py
For the Froemke Lab, they use Electrode 1 to record the waveform of the auditory stimulus, so we don't want to write this data as a neural response. @luiztauffer, I added an optional argument, `skip_electrodes`, to handle this, which is working. Do you think this approach is good or is there a better way?
> add option to skip electrodes

- src/nwb_conversion_tools/datainterfaces/__init__.py
- src/nwb_conversion_tools/datainterfaces/ecephys/kilo/kilodatainterface.py
- src/nwb_conversion_tools/tools/spikeinterface/spikeinterface.py
- tests/test_on_data/test_gin_ecephys.py
This should close #451 
Critically, this solves a bug in the recently `_add_waveforms` (see #472) when the return statement was not properly indented. 
I added a gin test for this that takes into account the fact that this is an object from `spikeinterface`.
> Add kilosort data interface

- .github/workflows/testing.yml
- src/nwb_conversion_tools/tools/data_transfers.py
- tests/test_internals/test_tools.py
Here is a working minimal helper function for evaluating the size of a directory on a globus endpoint.
Our CI may take some configuring to get the test to work, but the test passes on a system with an authenticated local endpoint.
(i) Other approaches:
(a) datalad - there has been a small amount of work in the past trying to get this working (https://github.com/datalad/datalad/issues/3758) which requires git-annex compatibility with globus, leading the development of  https://github.com/CONP-PCNO/git-annex-remote-globus which looked promising, but did not work out of the box on the DANDIHub due to the `no_browser` option not propagating up to it's higher dependencies, so while it may be possible to fix this eventually, I have no clue how long or how much work it would take. Suffice to say …
> [Feature] globus-specific size retrieval helper

- requirements-full.txt
- requirements-minimal.txt
- src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
Simple change that allows recording and sorting interfaces to run without a `nwbfile` by making the argument optional.
My understanding is that @bendichter used the same pattern in the ophys module for the current fromeke conversion.
> Make nwbfile argument optional in `run_conversion` for recording and sorting interfaces

- src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
As I am building a gallery of examples (#495) I am having the conversion run at the level of the interfaces. 
Recently, we have changed the  `run_conversion` for recording and sorting interfaces so that a nwbfile is not required to run the conversion: #496
However, I realized that today that `BlackrockRecordingExtractorInterface` had its own method of `run_conversion` and therefore the changes in #496 did not propagate there.
This PR addressed this using a similar logic to the one in the recent spikeglx interface changes: #465
> Allow `BlackrockRecordingExtractorInterface` to do `run_conversion` with no nwbfile

- src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
Similar to #503 and to #496. I am building examples in #495 that require calling the `run_conversion` directly from the data interface. As things stand, to do this with a sortingextractor interface it is necessary to pre define an nwbfile. This PR solves this by adding to the function an argument for `save_path`.
> Allow sorting interface to `run_conversion` without a nwbfile

- src/nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
This is a follow-up of #505 as I failed to propagate the metadata over there (which indicates that there is some test missing).
This is required in #495 for the tests to work over there.
> Allow sorting interface to run_conversion without a nwbfile II

- src/nwb_conversion_tools/datainterfaces/__init__.py
- src/nwb_conversion_tools/datainterfaces/ecephys/kilosort/kilosortdatainterface.py
- tests/test_on_data/test_gin_ecephys.py
What was the reasoning behind this change? Please explain the changes briefly.
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```
> change name. The name of the sortware is "kilosort" not "kilo"

- docs/conversion_example_gallery.rst
I am removing the statement that says that the sortings are not in doctest.
> Remove incorrect statement about doc gallery

- src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
While I was trying to understand the movie interface to locate the bug described in #499 I did this small refactor which I think greatly improves the readability of the function. I wanted to push it so the work is not lost. It is basically just taking the function out of the `run_conversion` and improving variable naming to be less generic and more on-task.
> Small refactor of movie interface

- src/nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
- src/nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
Continuation of #516 for LFP interfaces.
Removal of docstring allows it to completely inherit the one from the parent, which is identical.
> [Refactor] standardize LFP conversion kwargs

- src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- tests/test_on_data/test_gin_ophys.py
- tests/test_on_data/test_metadata/test_scanimage_metadata.py
While working in the Seidemann conversion I have been prototyping a new ophys interface. I have noticed that there is some required metadata parameters (the device name in the imaging plane and the plane name in the TwoPhotonSeries) that our current defaults do not fill. This PR aligns the metadata behavior of `roieextractors` with the one `spikeinterface` (as libraries of `nwb-conversion-tools`) where the required metadata to run is pre-filled and updated if provided.
For some reason those were added manually in our `gin_test` so I removed them from there and that works as a test.
> Update default parameters for ophys

- src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
- src/nwb_conversion_tools/datainterfaces/ophys/basesegmentationextractorinterface.py
- tests/test_on_data/test_metadata_combinations.py
This is a test for #537 that I think can serve as a general boilerplate for similar combinations.  Right now I have only written the test.
Edit: The issue is now fixed and the data is aligned.
> Fix metadata combination of imaging and segmentation interfaces 

- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
This follows the PR in #535 and I think will be necessary for getting the metadata correctly.
This is mostly a refactoring of the `add_two_photon_series` and as a bonus we can get rid of the function `safe_update` and use `dict_deep_update` in every instance of it.
> Refactor of `add_two_photon_series`

- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- src/nwb_conversion_tools/utils/checks.py
- tests/test_internals/test_movie_interface.py
Small PR that is a continuation of #536 
The biggest change is the removal of `use_times` and handles this logic to`roiextractors` in the same way that we did with `spikeinterface`. 
Also, the definition of `calculate_regular_series_rate` is changed. The one in main is not calculating the rate but the period of the signal.
> Refactor of add_two_photon_series II

- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- tests/test_internals/test_roi_extractors_module.py
During the current conversion (Seidemann) I am getting duplicated device metadata where specifying the actual metadata for ophys does not overwrite the defaults. This PR has two goals:
1) Add unit tests for `add_devices` in `roieextractors` 
2) Modify the function in such a way that if metadata for ophys / device is passed the defaults are not included.
> Unit test `roiextractors.py` module `add device`

- requirements-full.txt
- requirements-minimal.txt
- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- src/nwb_conversion_tools/utils/checks.py
- tests/test_internals/test_roi_extractors_module.py
During the current conversion (Seidemann) I am getting duplicated device metadata where specifying the actual metadata for ophys does not overwrite the defaults. This is a follow up of #543 where I corrected the same for `add_device` and this is the analgous for `add_two_photon_series`:
Add unit tests for  `add_two_photon_series` in roieextractors
Modify the function in such a way that the metadata for ophys / device is passed the defaults are not included.
EDIT: This is doing the same change as #547 as well.
> Unit test `add_two_photon_series` in the `roiextractors.py` module  

- docs/conversion_examples_gallery/sorting/cellexplorer.rst
- docs/conversion_examples_gallery/sorting/kilosort.rst
- docs/conversion_examples_gallery/sorting/neuroscope.rst
- docs/conversion_examples_gallery/sorting/phy.rst
- tests/test_internals/test_si.py
This removes the `save_path` argument that is going to be deprecated in favor of the new `nwbfile_path` standard.
> Update conversion gallery to new parameters

- src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
By mistake I added Optional typing to some parameters that can't be None. This PR should address this by removing it.
> Remove optional typing in blackrock data interface

- src/nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
By mistake I added Optional typing to some parameters that can't be None. This PR should address this by removing it.
> Remove optional types in pphy sorting data interface

- requirements-full.txt
- requirements-minimal.txt
This should eliminate all the deprecation warnings. This should close #486
> Update spikeextractors version to latest

- .github/workflows/testing.yml
- requirements-full.txt
- src/nwb_conversion_tools/datainterfaces/ophys/scanimage/scanimageimaginginterface.py
Updating the `ScanImageImagingInterface` extractor to use `ScanImageTiffImagingExtractor` from roiextractors instead of `TiffImagingExtractor`.
> Scan image interface to use proper roiextractor

- tests/test_internals/test_tools.py
Trying to figure out why some of these tests that don't need to run on external forks are failing skip based on identical environment variable retrieval attempts
> testing CI from fork

- .github/workflows/testing.yml
@h-mayorquin This should prevent that error from happening in the future - my guess is chocolatey servers went down for a while, but there's no reason we should actually need to install it every time.
This PR only install git-annex if there is a need to update the cache.
> [Testing]: Bypass git-annex install if unneeded

- src/nwb_conversion_tools/tools/roiextractors/__init__.py
- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- tests/test_internals/test_roi_extractors_module.py
This is part of a join effort with @weiglszonja to refactor `write_segmentation` in the roiextractors module. This first PR does a couple of things:
1) It refactors the previously added function called `add_imaging_plane` and adds some unit tests.
2) The `add_imaging_plane` function is then used to refactor the `write_segmentation` function with some code reduction.
3) There are some other minor refactoring in documentation (add_device function) and style here and there.
> Refactor write segmentation I 

- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
A continuation of #601 and chained to it:
1) Some minor modification in the add_device function so a device is not created again if it already exists.
2) Code reduction in `write_segmentation` by using the `add_device` function.
3) Eliminate code to add the subject in the `write_segmentation`
4) Make the default metadata more flat in its definition.
> Refactor write segmentation II (use `add_devices`)

- requirements-full.txt
- requirements-minimal.txt
- src/nwb_conversion_tools/tools/roiextractors/__init__.py
- src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
- tests/test_internals/test_roi_extractors_module.py
This is related to #601 and #602
This PR deals with refactoring the part of the `write_segmentation` function that adds the summary images (mean and correlation). I refactored this by adding an extra function whose sole purpose is to perform this addition to nwb. I also added some tests for this newly introduced function.
Also removed an unnecessary warning statement that we had.
This requires the branch in the following PR in roiextractors:
https://github.com/catalystneuro/roiextractors/pull/179
The reason being that the dummy segmentation extractor required for testing is a recent addition and the latest commit (specified in the has) also added an option for having a dummy segmentation extractor without summary images. As this runs in both our internal and data tests it is required in …
> Refactor write segmentation III (add summary images)
