catalystneuro/nwb-conversion-tools

nwbn_conversion_tools/gui/classes/forms_general.py
nwbn_conversion_tools/gui/nwbn_conversion_gui.py

creates a group for custom extensions, such as [LabMetaData](https://github.com/ben-dichter-consulting/ndx-labmetadata-giocomo), that gets its fields dynamically populated from metadata.

Custom extension group

---

nwbn_conversion_tools/ephys/acquisition/ephys_acquisition2NWB.py

- correctly transform Recording channels properties to Nwb electrodes properties
- keep data format from source and properly add conversion and 
channel_conversion fields in ElectricalSeries

update and fixes for spikeglx2nwb

---

make_env.yml
nwbn_conversion_tools/gui/classes/collapsible_box.py
nwbn_conversion_tools/gui/classes/forms_base.py
nwbn_conversion_tools/gui/classes/forms_behavior.py
nwbn_conversion_tools/gui/classes/forms_ecephys.py
nwbn_conversion_tools/gui/classes/forms_general.py
nwbn_conversion_tools/gui/classes/forms_misc.py
nwbn_conversion_tools/gui/classes/forms_ophys.py
nwbn_conversion_tools/gui/nwbn_conversion_gui.py
setup.py

- added tabs to GUI, makes it possible to create other functionalities beyond metadata fields interaction
- added a tab for nwb-jupyter-widgets rendering, using Voila
- makes boxes collapsible (just some groups for now), improves visual cleanliness

Gui tabs, nwb widgets and collapsible boxes

---

nwbn_conversion_tools/gui/classes/forms_ophys.py

This PR will be considered finalized when the GUI:

FRET extensions

---

nwb_conversion_tools/gui/nwb_conversion_gui.py

source paths autopopulated. 
Also autopopulated the nwb file save location based on the current working directory. Can be changed by the user within gui.

auto populate source paths and nwbfile location, have yaml also supported

---

nwb_conversion_tools/gui/nwb_conversion_gui.py

- changes how forms get populated for required and non-required fields. 
- nwb-explorer within the gui is optional as there were some errors #39 
- #38

changes to nwb_conversion_gui module

---

README.md

removed broken link error

---

nwb_conversion_tools/baserecordingextractorinterface.py
nwb_conversion_tools/basesortingextractorinterface.py
nwb_conversion_tools/nwbconverter.py
nwb_conversion_tools/utils.py

They are theoretically not needed, and I'm not noticing any difference after removal. Pertains to issue #62 (https://github.com/catalystneuro/nwb-conversion-tools/issues/62).

removed deepcopies

---

nwb_conversion_tools/datainterfaces/__init__.py
nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
nwb_conversion_tools/spikeglxdatainterface.py

Relevant to the tank-lab-to-nwb project

added interface for spikeglx recording extractor

---

nwb_conversion_tools/datainterfaces/__init__.py
nwb_conversion_tools/datainterfaces/intandatainterface.py

@bendichter I'll add the get_metadata() funciton for this later today, just getting this up for now

added intan recording interface

---

nwb_conversion_tools/datainterfaces/sipickledatainterfaces.py

@alejoe91 Significant reduction in duplicated code for running the interface. I agree that long-term we should look into mix-ins for separating the internal class configuration (to adhere better to inheritance) from the common set of conversion functionality, but that will likely take a bit of debugging to streamline.

simplified pickle interface to rely on base recording/sorting extractors

---

nwb_conversion_tools/basedatainterface.py
nwb_conversion_tools/datainterfaces/intandatainterface.py
nwb_conversion_tools/nwbconverter.py
nwb_conversion_tools/utils.py
setup.py

@bendichter Just a couple fixes to get this running and debugged for both Mease and Tank.

Post merge fixes

---

nwb_conversion_tools/datainterfaces/__init__.py

import CEDRecordingInterface on init

import CEDRecordingInterface on init

---

setup.py

add `lxml` and `pyintan` requirements

add lxml and pyintan requirements

---

documentation/conversion_tools_structure.md
nwb_conversion_tools/basedatainterface.py
nwb_conversion_tools/baserecordingextractorinterface.py
nwb_conversion_tools/basesegmentationextractorinterface.py
nwb_conversion_tools/basesortingextractorinterface.py
nwb_conversion_tools/datainterfaces/intandatainterface.py
nwb_conversion_tools/datainterfaces/neuroscopedatainterface.py
nwb_conversion_tools/datainterfaces/sipickledatainterfaces.py
nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
nwb_conversion_tools/json_schema_utils.py
nwb_conversion_tools/nwbconverter.py
nwb_conversion_tools/utils.py
setup.py

@bendichter @luiztauffer Results of our meeting, minus the json validation (on the TODO list) and lazy imports. Probably best to do those on a different branch, I'll get started on them tomorrow.
Mostly name change standardization, a couple comments below on anything other than that.

New schema compliance

---

nwb_conversion_tools/baseimagingextractorinterface.py
nwb_conversion_tools/basesegmentationextractorinterface.py
setup.py

* add base for imaging and segmentation

* add roiextractors as dependency

---

nwb_conversion_tools/nwbconverter.py

source_data is a dictionary with NameDataInterfaces as keywords, not a list to be unpacked

source_data at converter init

---

nwb_conversion_tools/datainterfaces/intandatainterface.py

@bendichter Noticed the intan device names are instantiated by default

removed incorrect naming information for intan

---

nwb_conversion_tools/basedatainterface.py
nwb_conversion_tools/baseimagingextractorinterface.py
nwb_conversion_tools/basesegmentationextractorinterface.py
nwb_conversion_tools/datainterfaces/__init__.py
nwb_conversion_tools/datainterfaces/roiextractordatainterface.py

this branch adds get_metadata_schema(), get_metadata() for segmentationextractors

added segmentationextractor methods

---

nwb_conversion_tools/datainterfaces/ceddatainterface.py

@CodyCBakerPhD would you mind checking if this doesn't break the conversions on your side?

exclude smrx_ch_inds from source schema

---

nwb_conversion_tools/baselfpextractorinterface.py
nwb_conversion_tools/baserecordingextractorinterface.py
nwb_conversion_tools/nwbconverter.py
setup.py

@bendichter 
1. Cleaned up the recording subset approach a bit, so that it only calls the function if subsetting is to actually be performed
2. Improved optional annotation checking for primary converter `run_conversion`
3. Extended the primary converter `run_conversion` to allow file appending, and optional overwrite capability

Refactor recording subsets

---

nwb_conversion_tools/datainterfaces/__init__.py
tests/test_interfaces.py

* create list of all interfaces
* validate all interface schemas against json schema draft 7

test interface schemas

---

nwb_conversion_tools/utils.py

detects child fields for MultiContainerInterface classes

detect child fields in multicontainerinterfaces

---

nwb_conversion_tools/utils.py

small fix on schema

---

nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py

@bendichter Small fix to the SpikeGLX thing for the current version of the tank repo to work

small fix for spikeglx with subrecording

---

nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py

Extract session_start_time from SpikeGLX meta file

Add session_start_time to SpikeGLXRecordingInterface

---

nwb_conversion_tools/baseimagingextractorinterface.py
nwb_conversion_tools/basesegmentationextractorinterface.py
nwb_conversion_tools/datainterfaces/__init__.py
nwb_conversion_tools/datainterfaces/imagingextractorinterface.py
requirements.txt

adding interfaces for imaging extractors

Imaging extractor interfaces

---

nwb_conversion_tools/datainterfaces/phydatainterface.py

@bendichter Simple interface for Phy -  needed for PetersenP dataset.

added phy sorting interface

---

nwb_conversion_tools/baserecordingextractorinterface.py
nwb_conversion_tools/basesortingextractorinterface.py
nwb_conversion_tools/datainterfaces/__init__.py
nwb_conversion_tools/datainterfaces/blackrockdatainterface.py
nwb_conversion_tools/datainterfaces/interface_utils/brpylib.py
nwb_conversion_tools/datainterfaces/openephysdatainterface.py
nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
nwb_conversion_tools/json_schema_utils.py
nwb_conversion_tools/nwbconverter.py
requirements.txt
tests/test_interfaces.py

Data interface for Blackrock and OpenEphys

---

.github/CODE_OF_CONDUCT.rst
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
docs/contribute.rst

@bendichter Largely borrowed from the PyNWB format for such things - this should now auto-populate those windows when users want to raise an issue or submit a PR.

Add contribution guidelines

---

nwb_conversion_tools/conversion_tools.py
tests/test_tools.py
tutorials/simple-tutorial.ipynb

Given how often we make use of this function in individual conversions, I'd say its a valuable addition to our `conversion_tools`.

Add get_module

---

nwb_conversion_tools/baserecordingextractorinterface.py
nwb_conversion_tools/datainterfaces/blackrockdatainterface.py
nwb_conversion_tools/datainterfaces/openephysdatainterface.py
nwb_conversion_tools/datainterfaces/spikeglxdatainterface.py
nwb_conversion_tools/json_schema_utils.py

fixes for dicts and schema

---

nwb_conversion_tools/datainterfaces/axonadatainterface.py

Fix [this](https://github.com/catalystneuro/hussaini-lab-to-nwb/pull/1#issuecomment-847461966)
@sbuergers can you check if this would solve it?

get_metadata_schema for axona

---

README.md

add pypi badge to readme

---

.github/workflows/ci-development.yml
.github/workflows/ci-production.yml

This was missing from the last PR, sorry. Improved Action title name and steps description.
We're now able to see from the summary pop-up window which pipeline failed/passed.
Look at the Github actions shortcut icon.

better action description and step names

---

docs/developer_guide.rst
docs/part01_core_nwb.rst
docs/part02_nwb_apis.rst
docs/part03_format_conversions.md

A few sentences in the documentation need to be read twice to be understood. Here are some improvement proposals. Feel free to suggest alternative wording.

[Doc] Small suggestions to improve readability

---

requirements.txt

Fix the versions that will pass the tests for production.
Observe CI results.

Fix req prod

---

nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
tests/test_gin.py

GIN data has been available for basic Neuroscope recordings for some time; finally getting around to adding it here to verify the metadata is being handled correctly and roundtrip works without error.
GIN tests added, interface debugged.
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

Add Neuroscope GIN

---

nwb_conversion_tools/__init__.py
nwb_conversion_tools/datainterfaces/ecephys/axona/axonadatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/openephys/openephysdatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/spikegadgets/spikegadgetsdatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
nwb_conversion_tools/datainterfaces/ecephys/spikeinterface/sipickledatainterfaces.py
nwb_conversion_tools/utils/json_schema.py

@luiztauffer If you could check this works OK with your stuff
PR #213 introduced the concept of automating file vs. folder path detection in source schema assignment from our own locally controlled method signatures. The current implementation uses `typing.TypeVar` to built specific annotation types for this purpose, read more at
- https://stackoverflow.com/questions/58755948/what-is-the-difference-between-typevar-and-newtype
- https://www.python.org/dev/peps/pep-0484/#newtype-helper-function
- https://mypy.readthedocs.io/en/stable/more_types.html#newtypes
I had tried Ben's method suggested in a meeting of
```
PathType = Union[str, Path]
class FilePathType(PathType):
pass
```
but couldn't quite get the inheritance behavior to mesh with the typing and signatures from annotations, even once …

Improve file vs folder annotations

---

nwb_conversion_tools/utils/json_schema.py

fix #244 
Issue #244 
```
from nwb_conversion_tools import OpenEphysRecordingExtractorInterface
OpenEphysRecordingExtractorInterface.get_source_schema()
```

fix source_data_schema

---

nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
tests/test_gin.py

This is the feature that @luiztauffer suggested in #243 .

autopick nsx_to_load from filename

---

nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py

@h-mayorquin found some new issues when attempting to use the CellExplorerInterface. The extractor worked this time (unlike the previous conversion), which revealed further issues regarding metadata that had not been updated since previous refactors to handling.
I'll assign @h-mayorquin to review, if it works for him then I'll merge the unit property fix this relies on first, then assign this to master.
I'm working with Julia as we speak to get some example CellExplorer data up on GIN so we can add coverage for it to auto-detect issues just like this.

Fix CellExplorer metadata

---

.github/workflows/full-tests-linux.yml
.github/workflows/full-tests-mac-windows.yml
.github/workflows/update-testing-data.yml
tests/test_gin.py

Adding coverage to all `ophys` interfaces, revealing some bugs that have changed over the months with various API changes.
Thanks to @Saksham20 fixing the GIN for this data, the caching CI now checks for updates every night along with the ecephys data.
I've then added two simple `Imaging` and `Segmentation` interfaces to the `test_gin.py` so @cechava can begin investigating a fix. Will add all the others we currently support later today.

Add ophys GIN

---

tests/test_on_data/test_gin.py

Restoring Axona tests to the CI.

Restore axona tests

---

nwb_conversion_tools/datainterfaces/ecephys/ced/ceddatainterface.py
tests/test_internals/test_interfaces.py

Restoring CED tests and version assertion.

Restoring CED tests

---

nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py

Restored Neuroscope fixes

---

nwb_conversion_tools/datainterfaces/ecephys/cellexplorer/cellexplorerdatainterface.py

Restore cell explorer fixes

---

nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
nwb_conversion_tools/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py
tests/test_on_data/test_gin.py

@Saksham20 @bendichter 
This PR introduces new tests to ensure LFP data is added to the intended processing module by default, and adds Axona LFP tests to ensure coverage for this.
Tests added to `test_gin.py`

Add LFP tests

---

requirements-full.txt
tests/test_internals/test_si.py

attempt to fix pynwb 2.0.0 tests
What was the reasoning behind this change? Please explain the changes briefly.
```
Show here how to reproduce the new behavior (can be a bug fix or a new feature)
```

change example prop to float

---

nwb_conversion_tools/utils/spike_interface.py

Updating docstrings, annotation typing, and required vs. optional behavior for inputs across the helper functions to make the new return behavior clearer.
It's on the long-term To-Do list to add many tests the these assertions are actually triggered.

Update docs and arguments for NWBFile object

---

README.md

fix #378 
Requested changes by @bendichter to instruct new users on how to run GIN tests locally on their own system.

Update README for GIN tests

---

nwb_conversion_tools/utils/spike_interface.py

@alejoe91 Suggestions for PR #371; maintains the writing of `unit_spike_features` in the case where the passed object is a `SortingExtractor`. I do believe this code can be efficiently refactored from its current state for non-waveform related data, but best to do that in a subsequent PR.

Suggestions: update write_sorting only

---

tests/test_internals/test_interfaces.py
tests/test_internals/test_movie_interface.py

Alleviating changelog differences from the simple moving of testing functions into a file file for PR #372

Moving some movie interface test functions

---

.github/workflows/testing-linux.yml
.github/workflows/testing-mac.yml
.github/workflows/testing-windows.yml

CI broke overnight due to pip version update triggering some kind of node error with the Github Action configuration. Testing to see if this fixes it.

Fix sudden install issues

---

tests/test_internals/test_si.py

@h-mayorquin Here are those suggestions I said I'd send your way with regards to improving the design of the new test class for appending electrode tables, and eventually what all those SI tests ought to look like for optimal performance and readability.
Let me know if you have any questions about anything.

Channel name testing suggestions

---

tests/test_on_data/test_gin_ecephys.py
tests/test_on_data/test_gin_ophys.py

Quick PR requested by @bendichter at the end of #413 .

removed soft import logic for parameterized

---

docs/_static/css/custom.css
docs/conf.py

add css for arg formatting

---

docs/api/tools.roiextractors.rst
docs/api/tools.rst
docs/api/tools.spikeinterface.rst
docs/api/tools.yaml_to_nwb_conversion.rst
docs/index.rst
nwb_conversion_tools/datainterfaces/ecephys/baselfpextractorinterface.py
nwb_conversion_tools/datainterfaces/ecephys/baserecordingextractorinterface.py
nwb_conversion_tools/datainterfaces/ecephys/basesortingextractorinterface.py
nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py

Added an API display functionality for the `nwb_conversion_tools.tools` in the documentation.

added api for tools in documentation

---

docs/data_interface.rst
docs/index.rst
docs/tutorials.rst
docs/user_guide.rst
tutorials/detailed-tutorial.ipynb
tutorials/simple-tutorial.ipynb

Updated the tutorials to ensure that they run and aligned them with their respective tests.

Update tutorials and add them to the documentation

---

.github/workflows/testing.yml
requirements-full.txt
requirements-minimal.txt
src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
tests/test_on_data/test_gin_behavior.py

Testing pinning exact version of roi extractors

pin version of roiextractors

---

src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py
src/nwb_conversion_tools/datainterfaces/ophys/tiff/tiffdatainterface.py

add default values to run_conversion so that you can run it without inputting an NWBFile

add default values to run_conversion 

---

.github/workflows/testing.yml
src/nwb_conversion_tools/tools/data_transfers.py
tests/test_internals/test_tools.py

Finally got this working - tests are passing on any local device logged into globus.
Depends on the process management helpers in #492, which I've now made non-private since it's proving quite useful generally. (@h-mayorquin should be happy to hear it uses `subprocess` instead of `os`)
This is the final item required to fully automated the Tingley conversion, which I'll start doing now.

[Feature] Automated globus transfer

---

.github/workflows/testing.yml

New cache is now failing on Linux as well, trying to resolve: https://github.com/catalystneuro/nwb-conversion-tools/runs/6375519127?check_suite_focus=true

[Bug] Trying to fix datalad for new cache

---

tests/test_internals/test_movie_interface.py

I spent some time looking for the CI bug described in #499. 
I mainly tested if the bug was caused by some shallow copy without success. 
There remain three possible culprits:
1. The `VideoCaptureContext` doing some update by reference to the files.
2. Some parallel access coincidence in the temporal directories on the CI.
3. Some deep_dict_update trickery that modifies the `starting_times` (see the accepted answer of this post https://stackoverflow.com/questions/17873384/how-to-deep-copy-a-list).
I will change the `starting_times` of the `test_movie_interface` to be fixed and non-random and the hope is that this reduces the incidence of the bug as it did for the `test_gin_behavior` which we haven not seen. 
At some point in the future when time allows and if the bug persists I will try …

Refactor test movie interface for CI bug

---

.github/workflows/testing.yml
.github/workflows/update-caches.yml
requirements-full.txt
requirements-minimal.txt
src/nwb_conversion_tools/datainterfaces/behavior/movie/moviedatainterface.py
tests/test_on_data/test_gin_behavior.py

The goal of this PR is to pin down the error that we are getting in #531.
I did a small refactor in the test that is failing to see if the error still appears / is reproducible here.

Small refactor of `test_gin_behavior` to pin new CI error

---

src/nwb_conversion_tools/tools/roiextractors/roiextractors.py

A small fix for `write_segmentation` to avoid writing response series consisting of only zero values.

Added check to avoid adding roi response series with only 0 values

---

requirements-full.txt
requirements-minimal.txt
setup.py
src/nwb_conversion_tools/tools/roiextractors/roiextractors.py
tests/test_internals/test_roi_extractors_module.py

This solves my problem within the current conversion. Proper metadata tests should be done for `write_segmentation` but I guess that will come after or together with the plan refactoring.

Further ophys metadata fixes

---

.github/workflows/testing.yml
tests/test_on_data/test_gin_ecephys.py
tests/test_on_data/test_metadata/test_spikeglx_metadata.py

Recent changes to the ephy_testing_data have caused some data tests to start failing. Investigating causes and workarounds now (suspect it is an improperly stubbed file).

Debug new ephy_testing_data

---

src/nwb_conversion_tools/datainterfaces/ophys/baseimagingextractorinterface.py

Make imaging extrator interface an abstract class

---

src/nwb_conversion_tools/datainterfaces/ecephys/blackrock/blackrockdatainterface.py
tests/test_on_data/test_gin_ecephys.py

As in the title. This is in the context of #500

Add spikeinterface support to `BlackrockRecordingExtractorInterface`

---

src/nwb_conversion_tools/datainterfaces/ecephys/phy/phydatainterface.py
tests/test_on_data/test_gin_ecephys.py

As stated in the title. Linked to https://github.com/catalystneuro/nwb-conversion-tools/issues/500.

Add spikeinterface support to `PhySortingInterface`

---

tests/test_internals/test_si.py

Small PR to reduce warnings in the testing suite.

Added timezone to session start time in add_units_table tests

---

src/nwb_conversion_tools/datainterfaces/ecephys/intan/intandatainterface.py

Added docstring to intan and some refactoring of the`get_metadat` function. This should be done after #561.

Added docstring and refactor metadata to `IntanRecordingInterface`

---

src/nwb_conversion_tools/datainterfaces/ecephys/neuroscope/neuroscopedatainterface.py

Remove the wrong optional typing in Neuroscope.

Remove optional typing in neuroscope

---

src/nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py

In the context of https://github.com/catalystneuro/nwb-conversion-tools/issues/500. This is a refactor to ensure that everything propagates well with the new recording interface. I will chain a PR to this introducing support for `spikeinterface`.

Refactor neuralynx before adding support for spikeinterface

---

src/nwb_conversion_tools/datainterfaces/ecephys/neuralynx/neuralynxdatainterface.py
tests/test_on_data/test_gin_ecephys.py
tests/test_on_data/test_metadata/test_neuralynx_metadata.py

This add supports as in https://github.com/catalystneuro/nwb-conversion-tools/issues/500.
Also, this should come after #577

Add spike interface support to neuralynx
